line.bot:
  channel-token: ea74c210a910c0dd8e22041273f0dd5e
  channel-secret: dK2vVVNMwfM9LpESDP5ZO+NSdG95rR7/ZMDMboZykGrz7PfIc36wurdMV5hruEg43LLlThWM4tZdT4cUQ03SSTjivHDNbQabySkuOe+G0bNrTboNIQ5ZgllcQ1KIlnTYcUOQwIkgYLBIXQE45r9+3gdB04t89/1O/w1cDnyilFU=
  handler.path: /callback
#server:
#  port: 8801
line:
  bot:
    handler:
      enabled: true
